BEGIN TRANSACTION;
insert into genre (id, name) values (01, 'fantasy');
insert into genre (id, name) values (02, 'science-fiction');
insert into genre (id, name) values (03, 'action-adventure');
insert into genre (id, name) values (04, 'horror');
insert into genre (id, name) values (05, 'thriller');
insert into genre (id, name) values (06, 'historical-fiction');
insert into genre (id, name) values (07, 'short-story');
insert into genre (id, name) values (08, 'biography');
insert into genre (id, name) values (09, 'history');
insert into genre (id, name) values (10, 'essay');
COMMIT;
