BEGIN TRANSACTION;
insert into piece (id, title) values (1, 'The Hitchhikers Guide to the Galaxy');
insert into piece (id, title) values (2, 'The Restaurant at the End of the Universe');
insert into piece (id, title) values (3, 'Life, the Universe and Everything');
insert into piece (id, title) values (4, 'So Long, and Thanks for All the Fish');
insert into piece (id, title) values (5, 'Recursion');
insert into piece (id, title) values (6, 'Shelter In The East');
insert into piece (id, title) values (7, 'Cleaning Up The Abyss');
insert into piece (id, title) values (8, 'Laughing At My Future');
insert into piece (id, title) values (9, 'Hurt By History');
insert into piece (id, title) values (10, 'Life At The Light');
insert into piece (id, title) values (11, 'Preparing For My Destiny');
insert into piece (id, title) values (12, 'Shelter At The Animals');
insert into piece (id, title) values (13, 'Losing The Sun');
insert into piece (id, title) values (14, 'Belonging To My Wife');
insert into piece (id, title) values (15, 'Battle Of The Maze');
insert into piece (id, title) values (16, 'Growing In My Enemies');
insert into piece (id, title) values (17, 'Blood At Secrets');
insert into piece (id, title) values (18, 'Death At The Animals');
insert into piece (id, title) values (19, 'Forsaken By The Light');
insert into piece (id, title) values (20, 'Promises Of The Light');
insert into piece (id, title) values (21, 'Dead At Secrets');
insert into piece (id, title) values (22, 'Enter The Town');
insert into piece (id, title) values (23, 'Visiting The King');
insert into piece (id, title) values (24, 'Deceiving The North');
insert into piece (id, title) values (25, 'Eating At Technology');
insert into piece (id, title) values (26, 'Sounds Of The Apocolypse');
insert into piece (id, title) values (27, 'Pleasing The Fires');
insert into piece (id, title) values (28, 'Fade Into The Sun');
insert into piece (id, title) values (29, 'Destroying My Past');
insert into piece (id, title) values (30, 'Opponent Of Freedom');
insert into piece (id, title) values (31, 'Admiring The Titans');
insert into piece (id, title) values (32, 'Kicking Dreams');
insert into piece (id, title) values (33, 'Invited By The End');
insert into piece (id, title) values (34, 'Fade Into The World');
insert into piece (id, title) values (35, 'Bravery In Dreams');
insert into piece (id, title) values (36, 'Reach Of The Fog');
insert into piece (id, title) values (37, 'Vanishing Into The Commander');
insert into piece (id, title) values (38, 'Guarded By The Hunter');
insert into piece (id, title) values (39, 'Eliminating My Home');
insert into piece (id, title) values (40, 'Kicking My Friends');
insert into piece (id, title) values (41, 'Still Breathing In The Commander');
insert into piece (id, title) values (42, 'Breath Of The Castle');
insert into piece (id, title) values (43, 'Pleasing My Family');
insert into piece (id, title) values (44, 'Signs Of The Maze');
insert into piece (id, title) values (45, 'Sailing Into Eternity');
insert into piece (id, title) values (46, 'Kicking Dreams');
insert into piece (id, title) values (47, 'Losing The Sun');
insert into piece (id, title) values (48, 'Praised By The Abyss');
insert into piece (id, title) values (49, 'Breaking The North');
insert into piece (id, title) values (50, 'Right About The Forest');
insert into piece (id, title) values (51, 'Travel To The Hunter');
insert into piece (id, title) values (52, 'Signs At The Titans');
insert into piece (id, title) values (53, 'Growing In The Future');
insert into piece (id, title) values (54, 'Eliminating The Animals');
insert into piece (id, title) values (55, 'Raised By The Mist');
insert into piece (id, title) values (56, 'Scared At My End');
insert into piece (id, title) values (57, 'Crying In The Abyss');
insert into piece (id, title) values (58, 'Breath Of The Town');
insert into piece (id, title) values (59, 'Prepare For The Stars');
insert into piece (id, title) values (60, 'Confessions Of The Dark');
insert into piece (id, title) values (61, 'Helping The Commander');
insert into piece (id, title) values (62, 'Lurking In The Elements');
insert into piece (id, title) values (63, 'Eliminating The Light');
insert into piece (id, title) values (64, 'Eliminating The Demons');
insert into piece (id, title) values (65, 'Deceiving The Future');
insert into piece (id, title) values (66, 'Challenging My Dreams');
insert into piece (id, title) values (67, 'Eliminating The Moon');
insert into piece (id, title) values (68, 'Never Trust Eternity');
insert into piece (id, title) values (69, 'Binding To The Past');
insert into piece (id, title) values (70, 'Promises Of The Light');
insert into piece (id, title) values (71, 'Possessed By The Castle');
insert into piece (id, title) values (72, 'Preparing For My Destiny');
insert into piece (id, title) values (73, 'Shelter At The King');
insert into piece (id, title) values (74, 'Avoiding The Maze');
insert into piece (id, title) values (75, 'Escaping The End');
insert into piece (id, title) values (76, 'Fade Into The Ocean');
insert into piece (id, title) values (77, 'Temptations Of The Nation');
insert into piece (id, title) values (78, 'Lurking In The Shadows');
insert into piece (id, title) values (79, 'Escape The West');
insert into piece (id, title) values (80, 'Bravery In The Depthsiving With The Licking Thorns');
COMMIT;
